# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pushkin', '0021_auto_20160531_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='argument',
            field=models.ManyToManyField(to='pushkin.CommandArgument'),
        ),
    ]
