# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pushkin', '0022_auto_20160612_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='argument',
            new_name='arguments',
        ),
    ]
