# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pushkin', '0023_auto_20160613_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='authparam',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
