# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushkin', '0029_auto_20160617_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
