# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushkin', '0030_auto_20160628_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='auth',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pushkin.AuthParam'),
            preserve_default=False,
        ),
    ]
